<?php

function tap_menu() {

  $items['tourml/tour/%node'] = array(
    'page callback' => 'tap_tourml_export',
    'page arguments' => array('node', 2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'tap.tourml.inc',
  );

  $items['node/%node/tourml_xml'] = array(
    'title' => 'TourML XML',
    'page callback' => 'tap_tourml_view',
    'page arguments' => array(1, 2),
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'tap.tourml.inc',
  );

  $items['node/%node/tourml_bundle'] = array(
    'title' => 'TourML Bundle',
    'page callback' => 'tap_tourml_view',
    'page arguments' => array(1, 2),
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'tap.tourml.inc',
  );

  return $items;
}

/**
 * Implements hook_entity_info_alter()
 */
function tap_entity_info_alter(&$entity_info) {
    $entity_info['node']['view modes']['tourml_xml'] = array(
        'label'             => t('TourML XML'),
        'custom settings'   => TRUE,
    ); 

    $entity_info['node']['view modes']['tourml_bundle'] = array(
        'label'             => t('TourML Bundle'),
        'custom settings'   => TRUE,
    );
}

/**
 * Implements hook_node_view()
 */
function tap_node_view($node, $view_mode, $langcode) {
    switch($view_mode) {
        case 'tourml_xml':
        case 'tourml_bundle':
            foreach (element_children($node->content) as $key) {
                _tap_tourml_field_formatter($node->content[$key], $view_mode);
            }
            break;
    }
}

function tap_block_info() {
  $blocks['addstop'] = array(
    'info' => t('Add Stop'),
  );
  return $blocks;
}

function tap_block_view($delta = '') {
  switch ($delta) {
    case 'addstop':
      $block['subject'] = t('Add Stop');
      $block['content'] = tap_block_contents($delta);
      break;
  }
  return $block;
}

function tap_block_contents($delta) {
  switch ($delta) {
    case 'addstop':

      $options = array();
//    $options = (arg(0) == 'node' && is_numeric(arg(1))) ? array('query' => 'destination='.$_GET['q']) : array();
      $links = array(
        l('Image Stop', 'node/add/tour-image-stop', $options),
        l('Video Stop', 'node/add/tour-video-stop', $options),
        l('Audio Stop', 'node/add/tour-audio-stop', $options),
        l('Stop Group', 'node/add/tour-stop-group', $options),
      );
      return array('#markup' => theme('item_list', array('items' => $links)));
  }
}


/*****************************
 * Helper functions
 ****************************/

/**
 * Prepares a field to be formatted for a tourml export
 *
 * @param $field: a themable field array from $node->content
 * @param $type: The type of formatter to use (tour_xml/tour_bundle/etc)
 */
function _tap_tourml_field_formatter(&$field, $type) {
    if ($field['#theme'] == 'field') {
        $field['#formatter'] = $field['#field_type']  . '_' . $type;
    }
}
