<?php

/************************************
 * Drupal Hooks
 */

/**
 * Implements hook_menu()
 */
function tap_menu() {

  $items['tourml/tour/%node'] = array(
    'page callback' => 'tap_tourml_export',
    'page arguments' => array('node', 2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'tap.tourml.inc',
  );

  $items['node/%node/tourml_xml'] = array(
    'title' => 'TourML XML',
    'page callback' => 'node_view',
    'page arguments' => array(1, 2),
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'tap.tourml.inc',
  );

  $items['node/%node/tourml_bundle'] = array(
    'title' => 'TourML Bundle',
    'page callback' => 'node_view',
    'page arguments' => array(1, 2),
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'tap.tourml.inc',
  );

  return $items;
}

/******************************
 * Entities 
 */

/**
 * Implements hook_entity_info_alter()
 */
function tap_entity_info_alter(&$entity_info) {
    $entity_info['node']['view modes']['tourml_xml'] = array(
        'label'             => t('TourML XML'),
        'custom settings'   => TRUE,
    ); 

    $entity_info['node']['view modes']['tourml_bundle'] = array(
        'label'             => t('TourML Bundle'),
        'custom settings'   => TRUE,
    );
}

function tap_theme() {
    return array(
        'text_tourml_xml' => array(
            'variables' => array(
                'items' => array(),
            ),
            'file'  => 'tap.templates.inc',
            'template'  => 'templates/text-tourml-xml',
        ),
        'file_tourml_xml' => array(
            'variables' => array(
                'items' => array(),
            ),
            'file'  => 'tap.templates.inc',
            'template'  => 'templates/file-tourml-xml',
        ),
        'node_reference_tourml_xml' => array(
            'variables' => array(
                'items' => array(),
            ),
            'file'  => 'tap.templates.inc',
            'template'  => 'templates/node-reference-tourml-xml',
        ),
    );
}

/******************************
 * Fields 
 */

/**
 * Implements hook_field_formatter_info()
 */
function tap_field_formatter_info() {
    $formatters = array(
       'text_tourml_xml' => array(
            'label'         => t('Text TourML XML'),
            'field types'   => array('text', 'text_long', 'text_summary'),
            'module'        => 'tap',
        ),
        'file_tourml_xml' => array(
            'label'         => t('File TourML XML'),
            'field types'   => array('file'),
            'module'        => 'tap',
        ),
        'node_reference_tourml_xml' => array(
            'label'         => t('Node Reference TourML XML'),
            'field types'   => array('node_reference'),
            'module'        => 'tap',
        ),
    );
    return $formatters;
}

/**
 * Implements hook_field_display_alter()
 */
function tap_field_display_alter(&$display, $context) {
    switch($context['view_mode']) {
        case 'tourml_xml':
        case 'tourml_bundle':
            // Override the field formatter with our tap formatter
            $display['type']    = $display['module'] . '_' . $context['view_mode'];
            $display['module']  = 'tap';
            break;
    }
}

/**
 * Implements hook_field_formatter_view()
 */
function tap_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
    $element['#theme'] = $display['type'];
    return $element;
}

/******************************
 * Blocks
 */

/**
 * Implements hook_block_info()
 */
function tap_block_info() {
  $blocks['addstop'] = array(
    'info' => t('Add Stop'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view()
 */
function tap_block_view($delta = '') {
  switch ($delta) {
    case 'addstop':
      $block['subject'] = t('Add Stop');
      $block['content'] = tap_block_contents($delta);
      break;
  }
  return $block;
}

function tap_block_contents($delta) {
  switch ($delta) {
    case 'addstop':

      $options = array();
//    $options = (arg(0) == 'node' && is_numeric(arg(1))) ? array('query' => 'destination='.$_GET['q']) : array();
      $links = array(
        l('Image Stop', 'node/add/tour-image-stop', $options),
        l('Video Stop', 'node/add/tour-video-stop', $options),
        l('Audio Stop', 'node/add/tour-audio-stop', $options),
        l('Stop Group', 'node/add/tour-stop-group', $options),
      );
      return array('#markup' => theme('item_list', array('items' => $links)));
  }
}


/*****************************
 * Helper functions
 ****************************/
