<?php

define('TAP_BEACONS_VERSION', '0.1.0');

/**
 * Implements hook_menu()
 */
function tap_beacons_menu() {
    $items['admin/tap/beacons'] = array(
        'title'             => 'Beacons',
        'page callback'     => 'tap_beacons_admin_section',
        'access arguments'  => array('administer tap'),
        'type'              => MENU_LOCAL_TASK,
        'file'              => 'tap_beacons.admin.inc',
    );

    return $items;
}

/**
 * Implements hook_theme()
 */
function tap_beacons_theme() {

    $beacons = tap_beacons_get_beacons();

    $items = array(
        'tap_beacons_admin_content' => array(
            'variables' => array(
                'beacons_data' => $beacons,
            ),
            'template'  => 'templates/tap_beacons_template',
        ),
    );

    return $items;
}

/**
* Gets beacon data from DB
*/
function tap_beacons_get_beacons(){
    $query = 'SELECT uuid, major_num, minor_num FROM {tap_beacons}';

    $query_result = db_query($query);

    foreach ($query_result as $row) {
        $row_array[] = array($row->uuid, $row->major_num, $row->minor_num);
    }

    $table = array(
        '#theme' => 'table',
        '#header' => array(t('UUID'), t('Major Number'), t('Minor Number')),
        '#rows' => $row_array
    );

    return $table;
}


function tap_beacons_admin_section() {

    drupal_add_css(drupal_get_path('module', 'tap_beacons') . '/css/tap_beacons_style.css');
    drupal_add_js(drupal_get_path('module', 'tap_beacons') . '/js/tap_beacons_main.js');

    return theme('tap_beacons_admin_content');
}