<?php

define('TAP_BEACONS_VERSION', '0.1.0');

/**
 * Implements hook_menu()
 */
function tap_beacons_menu() {
    $items['admin/tap/beacons'] = array(
        'title'             => 'Beacons',
        'page callback'     => 'tap_beacons_admin_section',
        'access arguments'  => array('administer tap'),
        'type'              => MENU_LOCAL_TASK,
        'file'              => 'tap_beacons.admin.inc',
    );

    $items['admin/tap/beacons/add'] = array(
        'title'             => 'Add Beacons',
        'page callback'     => 'tap_beacons_admin_add',
        'access arguments'  => array('administer tap'),
        'file'              => 'tap_beacons.admin.inc',
    );

    $items['admin/tap/beacons/delete'] = array(
        'title'             => 'Delete Beacons',
        'page callback'     => 'tap_beacons_admin_delete',
        'access arguments'  => array('administer tap'),
        'file'              => 'tap_beacons.admin.inc',
    );

    $items['admin/tap/beacons/update'] = array(
        'title'             => 'Update Beacons',
        'page callback'     => 'tap_beacons_admin_update',
        'access arguments'  => array('administer tap'),
        'file'              => 'tap_beacons.admin.inc',
    );

    return $items;
}

/**
 * Implements hook_theme()
 */
function tap_beacons_theme() {

    $beacons = tap_beacons_get_beacons();

    $items = array(
        'tap_beacons_admin_content' => array(
            'variables' => array(
                'beacons_data' => $beacons,
            ),
            'template'  => 'templates/tap_beacons_template',
        ),
    );

    return $items;
}

/**
* Get beacon data from DB
*/
function tap_beacons_get_beacons(){

    // Get beacon data from DB
    $result = db_select('tap_beacons', 'b')
        ->fields('b', array('beacon_id', 'uuid', 'major_num', 'minor_num'))
        ->execute();

    // Loop through each row and store the formatted data
    foreach ($result as $row) {
        $anchor = '<a href="#" data-id="'. $row->beacon_id .'" class="tap-beacons-update-btn">edit</a> | ';
        $anchor .= '<a href="/?q=admin/tap/beacons/delete&id='. $row->beacon_id .'" class="tap-beacons-delete-btn">delete</a>';

        $row_array[] = array($row->uuid, $row->major_num, $row->minor_num, $anchor);
    }

    // Build table with data
    $table = array(
        '#theme' => 'table',
        '#header' => array(t('UUID'), t('Major Number'), t('Minor Number'), t('Operations')),
        '#rows' => $row_array
    );

    return $table;
}
