<?php

function tap_webapp_menu() {
    $items['node/%node/web-app'] = array(
        'title'             => 'TAP Web-App Preview',
        'page callback'     => 'tap_webapp_preview',
        'page arguments'    => array(1),
        'access arguments'  => array('access content'),
        'type'              => MENU_LOCAL_TASK
    );

    return $items;
}

function tap_webapp_theme() {

    $module_path = url(drupal_get_path('module', 'tap_webapp'), array('absolute' => true));
    $webapp_version = '0.1.0';
    $tap_version = '0.1.0';

    return array(
        'tap_webapp_preview' => array(
            'variables' => array(
                'tourml_path' => null,
                'webapp_css_path' => "$module_path/tap-webapp-$webapp_version/Tap-$tap_version.css",
                'webapp_dependencies_path' => "$module_path/tap-webapp-$webapp_version/Tap-$tap_version-dependencies.min.js",
                'webapp_js_path' => "$module_path/tap-webapp-$webapp_version/Tap-$tap_version.min.js",
            ),
            'template'  => 'templates/tap-webapp-preview',
        ),
    );
}

function tap_webapp_preview($node) {

    // First, find the tour that this node is in
    if ($node->type != 'tour') {
        $tour_nid = $node->field_tour['und'][0]['target_id'];
        if (!is_numeric($tour_nid)) {
            dpm('non-numeric tour id');
            return;
        } 
    } else {
        $tour_nid = $node->nid;
    }

    $tourMLuri = url('node/' . $tour_nid . '/tourml.xml');

    print theme('tap_webapp_preview', array('tourml_path' => $tourMLuri));

    die();
}
