<?php

define('TAP_WEBAPP_VERSION', '0.1.0');

/**
 * Implements hook_uninstall
 */
function tap_webapp_uninstall() {
    db_query("DELETE FROM {variable} WHERE name LIKE '%s%%'", 'tap_webapp');
}

/**
 * Implements hook_menu()
 */
function tap_webapp_menu() {

    $items['admin/tap/webapp'] = array(
        'title'             => 'Web App',
        'page callback'     => 'drupal_get_form',
        'page arguments'    => array('tap_webapp_admin_form'),
        'access arguments'  => array('administer tap'),
        'type'              => MENU_LOCAL_TASK,
        'file'              => 'tap_webapp.admin.inc',
    );

    $items['node/%node/web-app'] = array(
        'title'             => 'TAP Web-App Preview',
        'page callback'     => 'tap_webapp_preview',
        'page arguments'    => array(1),
        'access arguments'  => array('access content'),
        'type'              => MENU_LOCAL_TASK
    );

    return $items;
}

/**
 * Implements hook_theme()
 */
function tap_webapp_theme() {

    $items = array(
        'tap_webapp_preview' => array(
            'variables' => array(
                'tourml_path' => NULL,
                'webapp_endpoint' => NULL
            ),
            'template'  => 'templates/tap-webapp-preview',
        ),
    );

    return $items;
}

function tap_webapp_preview($node) {

    drupal_add_css(drupal_get_path('module', 'tap_webapp') . '/css/webapp_style.css');

    // First, find the tour that this node is in
    if ($node->type != 'tour' && $node->type != 'tour_set') {
        $tour_nid = $node->field_tour['und'][0]['target_id'];
        if (!is_numeric($tour_nid)) {
            return;
        } 
    }
    else {
        $tour_nid = $node->nid;
    }

    $tourMLuri = url('node/' . $tour_nid . '/tourml.xml', array('absolute' => TRUE));

    return theme('tap_webapp_preview', array('tourml_path' => $tourMLuri, 'webapp_endpoint' => variable_get('tap_webapp_endpoint', '')));
}
